# Site settings

title: "sen0rxol0's Website"
description: "sen0rxol0's Website/Blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itswalter.me" # the base hostname & protocol for your site
email_address: walterb.varela@gmail.com
cv_link: https://drive.google.com/open?id=0B1vkOn1fSCE5SU5oZVFUaFJROXM
twitter_username: sen0rxol0
github_username:  sen0rxol0


excerpt_separator: <!--excerptor-->

# Gems

# Exclude/Include folders/files from Conversion
include: ["assets"]

exclude: ["gulpfile.js", "node_modules", "package.json", "npm-debug.log", "Gemfile", "Gemfile.lock"]


# Build settings

collections:
  posts:
    permalink: /blog/:title/



#defaults:
#  -
#    scope:
#	  path: ""
#	  type: posts
#	values:
#	  layout: post
#	  permalink: /blog/:title/
