# Site settings

title: "sen0rxol0's Website"
description: "sen0rxol0's Website/Blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sen0rxol0.github.io" # the base hostname & protocol for your site
email_address: waltva.senpai@gmail.com
twitter_username: sen0rxol0
github_username:  sen0rxol0


# Build settings
excerpt_separator: <!--excerptor-->

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:title" 
      layout: "post"


# Gems

# Exclude/Include folders/files from Conversion
include: ["assets"]
